version: '3.8'
services:
  db:
    image: mysql:8.0.28
    environment:
      MYSQL_DATABASE: 'super-app'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql
  node:
    build:
      context: node/
      dockerfile: Dockerfile
  php:
    build:
      context: php/
      dockerfile: Dockerfile
    ports:
      - 8060:80
volumes:
  db: