name: CI 
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  Build_Docker:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4
        
      - name: Login to Docker Hub
        uses: docker/login-action@v3.1.0
        with:
          username: ${{ secrets.docker_user }}
          password: ${{ secrets.docker_pass }}

      - name: Build et push
        run: | 
          docker compose build
          docker compose up -d
          docker push  roaaak/super-app
